### ISSUE TITLE
Question: Trying to follow the tutorial, Invalid host in HTTP_REFERER after submit button

### ISSUE THREAD

**Issue by Geo-Ron** [tomolimo/processmaker#94] opened 2019-09-19 09:57 UTC
Current install:
-GLPI 9.4.3 on IIS with PHP7 and MariaDB
-Processmaker on the same server, IIS site with PHP 5.6.30 and the same MariaDB
-Processmaker 3.3.0-community-RE-1.6
-Processmaker plugin 3.6.5

After pressing the SUBMIT button from Tutorial 1, I receive following error:
![image](https://user-images.githubusercontent.com/23144316/65234278-8de49300-dad4-11e9-8b66-336ed2aff644.png)

Is this to be expected? Or do I have still an issue in my dev environment?

**Comment by tomolimo** [comment] 2019-09-19 10:05
Hello @Geo-Ron 
I think you still have an issue in the configuration of the url.
Could you do screen copies of the PM server configurations, and of the PM plugin configuration, and of GLPI configuration?
Thank you,
Regards,
Tomolimo

**Comment by Geo-Ron** [comment] 2019-09-19 10:55
Off course I can

![image](https://user-images.githubusercontent.com/23144316/65238228-8d4ffa80-dadc-11e9-96f5-207f1a35fe39.png)
![image](https://user-images.githubusercontent.com/23144316/65238324-b8d2e500-dadc-11e9-971f-5f550872ad85.png)

**Comment by tomolimo** [comment] 2019-09-19 10:56
Thank you,
And what about GLPI configuration?

**Comment by Geo-Ron** [comment] 2019-09-19 11:00
![image](https://user-images.githubusercontent.com/23144316/65238628-5e865400-dadd-11e9-8837-0cd02ff3bfb6.png)

this piece?

**Comment by tomolimo** [comment] 2019-09-19 11:02
yes, thank you,

Do you have any logs in the php-errors.log? In GLPI folder /files/_log/

Same question for PM server?

thank you

**Comment by Geo-Ron** [comment] 2019-09-19 12:26
`[19-Sep-2019 11:28:05 Europe/Amsterdam] PHP Notice:  Undefined index: GLPI_DOMAIN in D:\whereisthisfolder\processmaker-server\workflow\public_html\glpi\app.php on line 219`

```
[2019-09-18 20:27:31] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in D:\WhereIsThis\inc\toolbox.class.php line 659
  *** PHP Notice(8): Undefined index: taskcategories_id
  Backtrace :
  ...ns\processmaker\inc\processmaker.class.php:1712 
  ...ns\processmaker\inc\processmaker.class.php:1932 PluginProcessmakerProcessmaker->addTask()
  ...ns\processmaker\inc\processmaker.class.php:2881 PluginProcessmakerProcessmaker->add1stTask()
  ...ins\processmaker\front\processmaker.form.php:11 PluginProcessmakerProcessmaker->startNewCase()
  {"user":"9@MYSERVER"} 
[2019-09-18 20:27:31] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in D:\WhereIsThis\inc\toolbox.class.php line 659
  *** PHP Notice(8): Undefined index: plugin_processmaker_processes_id
  Backtrace :
  ...ns\processmaker\inc\processmaker.class.php:1715 
  ...ns\processmaker\inc\processmaker.class.php:1932 PluginProcessmakerProcessmaker->addTask()
  ...ns\processmaker\inc\processmaker.class.php:2881 PluginProcessmakerProcessmaker->add1stTask()
  ...ins\processmaker\front\processmaker.form.php:11 PluginProcessmakerProcessmaker->startNewCase()
  {"user":"9@MYSERVER","mem_usage":"0.001\", 3.93Mio)"} 
[2019-09-18 20:27:31] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in D:\WhereIsThis\inc\toolbox.class.php line 659
  *** PHP Notice(8): Undefined index: insert_task_comment
  Backtrace :
  ...ns\processmaker\inc\processmaker.class.php:1798 
  ...ns\processmaker\inc\processmaker.class.php:1932 PluginProcessmakerProcessmaker->addTask()
  ...ns\processmaker\inc\processmaker.class.php:2881 PluginProcessmakerProcessmaker->add1stTask()
  ...ins\processmaker\front\processmaker.form.php:11 PluginProcessmakerProcessmaker->startNewCase()
  {"user":"9@MYSERVER","mem_usage":"0.001\", 3.93Mio)"} 
[2019-09-18 20:27:31] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in D:\WhereIsThis\inc\toolbox.class.php line 659
  *** PHP Notice(8): Undefined index: hide_case_num_title
  Backtrace :
  ...ns\processmaker\inc\processmaker.class.php:1804 
  ...ns\processmaker\inc\processmaker.class.php:1932 PluginProcessmakerProcessmaker->addTask()
  ...ns\processmaker\inc\processmaker.class.php:2881 PluginProcessmakerProcessmaker->add1stTask()
  ...ins\processmaker\front\processmaker.form.php:11 PluginProcessmakerProcessmaker->startNewCase()
  {"user":"9@MYSERVER","mem_usage":"0.000\", 3.93Mio)"} 
[2019-09-18 20:27:31] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in D:\WhereIsThis\inc\toolbox.class.php line 659
  *** PHP Notice(8): Undefined index: id
  Backtrace :
  ...ins\processmaker\front\processmaker.form.php:29 
  {"user":"9@MYSERVER","mem_usage":"0.008\", 4.24Mio)"} 
[2019-09-18 20:36:05] glpiphplog.NOTICE: Dropdown::show() in D:\WhereIsThis\inc\dropdown.class.php line 84
Using a string in condition option is deprecated.  {"user":"9@MYSERVER"} 
[2019-09-18 20:36:05] glpiphplog.NOTICE: Dropdown::addNewCondition() in D:\WhereIsThis\inc\dropdown.class.php line 284
Using a string in dropdown condition is deprecated.  {"user":"9@MYSERVER","mem_usage":"0.001\", 3.57Mio)"} 
[2019-09-19 06:57:52] glpiphplog.NOTICE: Dropdown::show() in D:\WhereIsThis\inc\dropdown.class.php line 84
Using a string in condition option is deprecated.  {"user":"9@MYSERVER"} 
[2019-09-19 06:57:52] glpiphplog.NOTICE: Dropdown::addNewCondition() in D:\WhereIsThis\inc\dropdown.class.php line 284
Using a string in dropdown condition is deprecated.  {"user":"9@MYSERVER","mem_usage":"0.008\", 3.70Mio)"} 
[2019-09-19 07:20:05] glpiphplog.NOTICE: Dropdown::show() in D:\WhereIsThis\inc\dropdown.class.php line 84
Using a string in condition option is deprecated.  {"user":"9@MYSERVER"} 
[2019-09-19 07:20:05] glpiphplog.NOTICE: Dropdown::addNewCondition() in D:\WhereIsThis\inc\dropdown.class.php line 284
Using a string in dropdown condition is deprecated.  {"user":"9@MYSERVER","mem_usage":"0.001\", 3.71Mio)"} 
[2019-09-19 09:27:50] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in D:\WhereIsThis\inc\toolbox.class.php line 659
  *** PHP Notice(8): Undefined property: stdClass::$caseId
  Backtrace :
  plugins\processmaker\inc\case.class.php:373        
  plugins\processmaker\inc\case.class.php:585        PluginProcessmakerCase->showCaseProperties()
  plugins\processmaker\inc\case.class.php:1417       PluginProcessmakerCase::showCaseInfoTab()
  inc\commonglpi.class.php:475                       PluginProcessmakerCase->showForm()
  ajax\common.tabs.php:92                            CommonGLPI::displayStandardTab()
  {"user":"9@MYSERVER"} 
[2019-09-19 09:27:50] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in D:\WhereIsThis\inc\toolbox.class.php line 659
  *** PHP Notice(8): Undefined property: stdClass::$processName
  Backtrace :
  plugins\processmaker\inc\case.class.php:493        
  plugins\processmaker\inc\case.class.php:386        PluginProcessmakerCase->showShort()
  plugins\processmaker\inc\case.class.php:585        PluginProcessmakerCase->showCaseProperties()
  plugins\processmaker\inc\case.class.php:1417       PluginProcessmakerCase::showCaseInfoTab()
  inc\commonglpi.class.php:475                       PluginProcessmakerCase->showForm()
  ajax\common.tabs.php:92                            CommonGLPI::displayStandardTab()
  {"user":"9@MYSERVER","mem_usage":"0.001\", 4.02Mio)"} 
[2019-09-19 09:27:50] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in D:\WhereIsThis\inc\toolbox.class.php line 659
  *** PHP Notice(8): Undefined property: stdClass::$caseName
  Backtrace :
  plugins\processmaker\inc\case.class.php:497        
  plugins\processmaker\inc\case.class.php:386        PluginProcessmakerCase->showShort()
  plugins\processmaker\inc\case.class.php:585        PluginProcessmakerCase->showCaseProperties()
  plugins\processmaker\inc\case.class.php:1417       PluginProcessmakerCase::showCaseInfoTab()
  inc\commonglpi.class.php:475                       PluginProcessmakerCase->showForm()
  ajax\common.tabs.php:92                            CommonGLPI::displayStandardTab()
  {"user":"9@MYSERVER","mem_usage":"0.000\", 4.02Mio)"} 
[2019-09-19 09:27:50] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in D:\WhereIsThis\inc\toolbox.class.php line 659
  *** PHP Notice(8): Undefined property: stdClass::$caseNumber
  Backtrace :
  plugins\processmaker\inc\case.class.php:499        
  plugins\processmaker\inc\case.class.php:386        PluginProcessmakerCase->showShort()
  plugins\processmaker\inc\case.class.php:585        PluginProcessmakerCase->showCaseProperties()
  plugins\processmaker\inc\case.class.php:1417       PluginProcessmakerCase::showCaseInfoTab()
  inc\commonglpi.class.php:475                       PluginProcessmakerCase->showForm()
  ajax\common.tabs.php:92                            CommonGLPI::displayStandardTab()
  {"user":"9@MYSERVER","mem_usage":"0.000\", 4.02Mio)"} 
[2019-09-19 09:27:50] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in D:\WhereIsThis\inc\toolbox.class.php line 659
  *** PHP Notice(8): Undefined property: stdClass::$caseStatus
  Backtrace :
  plugins\processmaker\inc\case.class.php:500        
  plugins\processmaker\inc\case.class.php:386        PluginProcessmakerCase->showShort()
  plugins\processmaker\inc\case.class.php:585        PluginProcessmakerCase->showCaseProperties()
  plugins\processmaker\inc\case.class.php:1417       PluginProcessmakerCase::showCaseInfoTab()
  inc\commonglpi.class.php:475                       PluginProcessmakerCase->showForm()
  ajax\common.tabs.php:92                            CommonGLPI::displayStandardTab()
  {"user":"9@MYSERVER","mem_usage":"0.000\", 4.02Mio)"} 
[2019-09-19 09:27:50] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in D:\WhereIsThis\inc\toolbox.class.php line 659
  *** PHP Notice(8): Undefined property: stdClass::$caseId
  Backtrace :
  plugins\processmaker\inc\case.class.php:501        
  plugins\processmaker\inc\case.class.php:386        PluginProcessmakerCase->showShort()
  plugins\processmaker\inc\case.class.php:585        PluginProcessmakerCase->showCaseProperties()
  plugins\processmaker\inc\case.class.php:1417       PluginProcessmakerCase::showCaseInfoTab()
  inc\commonglpi.class.php:475                       PluginProcessmakerCase->showForm()
  ajax\common.tabs.php:92                            CommonGLPI::displayStandardTab()
  {"user":"9@MYSERVER","mem_usage":"0.000\", 4.02Mio)"} 
[2019-09-19 09:27:50] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in D:\WhereIsThis\inc\toolbox.class.php line 659
  *** PHP Notice(8): Undefined property: stdClass::$caseCreatorUserName
  Backtrace :
  plugins\processmaker\inc\case.class.php:502        
  plugins\processmaker\inc\case.class.php:386        PluginProcessmakerCase->showShort()
  plugins\processmaker\inc\case.class.php:585        PluginProcessmakerCase->showCaseProperties()
  plugins\processmaker\inc\case.class.php:1417       PluginProcessmakerCase::showCaseInfoTab()
  inc\commonglpi.class.php:475                       PluginProcessmakerCase->showForm()
  ajax\common.tabs.php:92                            CommonGLPI::displayStandardTab()
  {"user":"9@MYSERVER","mem_usage":"0.000\", 4.02Mio)"} 
[2019-09-19 09:27:50] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in D:\WhereIsThis\inc\toolbox.class.php line 659
  *** PHP Notice(8): Undefined property: stdClass::$createDate
  Backtrace :
  plugins\processmaker\inc\case.class.php:503        
  plugins\processmaker\inc\case.class.php:386        PluginProcessmakerCase->showShort()
  plugins\processmaker\inc\case.class.php:585        PluginProcessmakerCase->showCaseProperties()
  plugins\processmaker\inc\case.class.php:1417       PluginProcessmakerCase::showCaseInfoTab()
  inc\commonglpi.class.php:475                       PluginProcessmakerCase->showForm()
  ajax\common.tabs.php:92                            CommonGLPI::displayStandardTab()
  {"user":"9@MYSERVER","mem_usage":"0.000\", 4.02Mio)"} 
[2019-09-19 09:27:50] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in D:\WhereIsThis\inc\toolbox.class.php line 659
  *** PHP Notice(8): Undefined property: stdClass::$updateDate
  Backtrace :
  plugins\processmaker\inc\case.class.php:504        
  plugins\processmaker\inc\case.class.php:386        PluginProcessmakerCase->showShort()
  plugins\processmaker\inc\case.class.php:585        PluginProcessmakerCase->showCaseProperties()
  plugins\processmaker\inc\case.class.php:1417       PluginProcessmakerCase::showCaseInfoTab()
  inc\commonglpi.class.php:475                       PluginProcessmakerCase->showForm()
  ajax\common.tabs.php:92                            CommonGLPI::displayStandardTab()
  {"user":"9@MYSERVER","mem_usage":"0.000\", 4.02Mio)"} 
[2019-09-19 09:30:26] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in D:\WhereIsThis\inc\toolbox.class.php line 659
  *** PHP Notice(8): Undefined index: state
  Backtrace :
  plugins\actualtime\inc\task.class.php:487          
  plugins\actualtime\hook.php:35                     PluginActualtimeTask::preUpdate()
  inc\plugin.class.php:1112                          plugin_actualtime_item_update()
  inc\commondbtm.class.php:1361                      Plugin::doHook()
  plugins\processmaker\inc\case.class.php:285        CommonDBTM->update()
  plugins\processmaker\inc\case.class.php:256        PluginProcessmakerCase->reassignTask()
  ...ins\processmaker\front\processmaker.form.php:96 PluginProcessmakerCase->reassignCase()
  {"user":"9@MYSERVER"} 
[2019-09-19 09:30:40] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in D:\WhereIsThis\inc\toolbox.class.php line 659
  *** PHP Notice(8): Undefined index: state
  Backtrace :
  plugins\actualtime\inc\task.class.php:487          
  plugins\actualtime\hook.php:35                     PluginActualtimeTask::preUpdate()
  inc\plugin.class.php:1112                          plugin_actualtime_item_update()
  inc\commondbtm.class.php:1361                      Plugin::doHook()
  plugins\processmaker\inc\case.class.php:285        CommonDBTM->update()
  plugins\processmaker\inc\case.class.php:256        PluginProcessmakerCase->reassignTask()
  ...ins\processmaker\front\processmaker.form.php:96 PluginProcessmakerCase->reassignCase()
  {"user":"9@MYSERVER"} 
[2019-09-19 09:52:57] glpiphplog.NOTICE: Dropdown::show() in D:\WhereIsThis\inc\dropdown.class.php line 84
Using a string in condition option is deprecated.  {"user":"9@MYSERVER"} 
[2019-09-19 09:52:57] glpiphplog.NOTICE: Dropdown::addNewCondition() in D:\WhereIsThis\inc\dropdown.class.php line 284
Using a string in dropdown condition is deprecated.  {"user":"9@MYSERVER","mem_usage":"0.001\", 3.67Mio)"} 
[2019-09-19 09:53:06] glpiphplog.NOTICE: Dropdown::getDropdownValue() in D:\WhereIsThis\inc\dropdown.class.php line 2320
Please no longer use raw SQL for conditions!  {"user":"9@MYSERVER"} 

```

Some log extracts

**Comment by tomolimo** [comment] 2019-09-19 12:37
Looks like the param GLPI_DOMAIN is not passed by GLPI to PM...
Could you copy/paste the rewrite rule you've defined fro PM server in IIS?

**Comment by Geo-Ron** [comment] 2019-09-19 14:40
![image](https://user-images.githubusercontent.com/23144316/65254137-1a567c00-dafc-11e9-860e-cd16eac6a40e.png)

According to https://github.com/tomolimo/processmaker-server/wiki/Inbound-rewrite-rules this should be correct

**Comment by Geo-Ron** [comment] 2019-09-19 14:41
Sorry: you asked for a copy/paste:

```
       <rewrite>
            <rules>
                <rule name="ProcessMaker Rule" stopProcessing="true">
                    <match url="^.*/(.*)$" ignoreCase="true" />
                    <action type="Rewrite" url="glpi/app.php" />
                </rule>
            </rules>
        </rewrite>
```

**Comment by tomolimo** [comment] 2019-09-19 14:44
I got the same rule in my own instance

**Comment by tomolimo** [comment] 2019-09-19 14:48
Did you define the skins like describe here: https://github.com/tomolimo/processmaker-server/wiki/Skins?

**Comment by Geo-Ron** [comment] 2019-09-19 15:18
Yip
![image](https://user-images.githubusercontent.com/23144316/65257401-71128480-db01-11e9-9c83-b7c12d45f9c7.png)

**Comment by tomolimo** [comment] 2019-09-20 09:57
Hello @Geo-Ron 
Could you delete log file content and then retry to reproduce the error?
This should produce the same error message and a fresh log.
Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment] 2019-11-04 08:27
Hello @Geo-Ron 
I close this issue as there is no answer to last post.
Feel free to re-open when you'll need it.
Thank you
Regards,
Tomolimo

**Closed by tomolimo** 2019-11-04 08:27 UTC
