### ISSUE TITLE
View the 'Change log' and the 'Dynaforms'

### ISSUE THREAD

**Issue by alogez** [tomolimo/processmaker#26] opened 2017-05-19 11:13 UTC
Hello Tomolimo,

Nothing is displayed in this interface (IE, Chrome, Mozilla browser).

![image](https://cloud.githubusercontent.com/assets/13637446/26245247/40592d9c-3ca4-11e7-9d65-ceb8a96f05af.png)
All the setting are done, thanks to your tutorial ([link](https://github.com/tomolimo/processmaker/wiki/How-to-view-the-%27Change-log%27-and-the-%27Dynaforms%27)).

![image](https://cloud.githubusercontent.com/assets/13637446/26245417/0e64f9be-3ca5-11e7-966a-31ce5df5e8fa.png)

In this last display, I can't check the group (GLPI Users).

![image](https://cloud.githubusercontent.com/assets/13637446/26245476/47b10fe6-3ca5-11e7-8765-b0ca86570992.png)

![image](https://cloud.githubusercontent.com/assets/13637446/26245497/614d1fda-3ca5-11e7-9d58-e90a4aefa87c.png)

Have you got an idea?

Thanks in advance.

Alogez.

**Comment by tomolimo** [comment] 2017-05-19 11:22
Hello @alogez 
Could you check that the group is Active and that it contains users like shown below?
![image](https://cloud.githubusercontent.com/assets/7569958/26245807/2fb1a09a-3c96-11e7-84f8-96fd26a2303a.png)

**Comment by alogez** [comment] 2017-05-19 11:32
Hello @tomolimo, 

This setting is on.
![image](https://cloud.githubusercontent.com/assets/13637446/26246071/4a499356-3ca8-11e7-8079-ecdbda63c7d3.png)

Alogez.

**Comment by tomolimo** [comment] 2017-05-19 11:35
Could you check this:
https://github.com/tomolimo/processmaker-server/wiki/Roles

and especially this:
https://github.com/tomolimo/processmaker-server/wiki/Roles#processmaker_operator

thank you,

**Comment by alogez** [comment] 2017-05-19 11:38
@tomolimo, 

Thanks again.
I also thought about it.
The operator role has been over granted, for test, without success.

Alogez.

**Comment by tomolimo** [comment] 2017-05-19 11:41
Then we need to trace network exchanges to get the hidden error.
Could you go to F12 (="developper tools") in Chrome, go to 'network' panel, and re-try to select the 'GLPI users' in the permission dialog box?

**Comment by alogez** [comment] 2017-05-19 11:47
@tomolimo,
What would you need?

![image](https://cloud.githubusercontent.com/assets/13637446/26246444/425d9d7a-3caa-11e7-8494-17c472f0c8f8.png)

Alogez.

**Comment by tomolimo** [comment] 2017-05-19 11:50
click on the last workflow, and see if there is no error anywhere in the response

**Comment by alogez** [comment] 2017-05-19 12:11
@tomolimo, 
I force to type "GLPI Users" ==> then I get this error.
No mention for grp_uid.

![image](https://cloud.githubusercontent.com/assets/13637446/26247111/72a17b2a-3cad-11e7-8a10-1535f776991d.png)

I have also tried => No group appears; only the users.
![image](https://cloud.githubusercontent.com/assets/13637446/26247201/d39caa9e-3cad-11e7-9366-95b60d528b33.png)


Alogez.

**Comment by tomolimo** [comment] 2017-05-19 12:17
Seems like there is something wrong in the configuration of the server :(
could you list the users in the group?
Are they all active?

**Comment by alogez** [comment] 2017-05-19 12:20
@tomolimo, 
They are active.
![image](https://cloud.githubusercontent.com/assets/13637446/26247454/fcc1bc42-3cae-11e7-822d-199ae31b3df4.png)
Alogez.

**Comment by tomolimo** [comment] 2017-05-19 12:31
I really don't have any idea :(
As I can't reproduce this behavior I can't help you.
If you agree, you may send your process: by exporting it into a pmx file, and send it to my corporate email.
and also a backup of the DB, I'll try to reproduce your environment.

**Comment by tomolimo** [comment] 2018-08-03 11:06
Hello,
Closed as I got no news, feel free to reopen if you need.
Thank you,
Regards,
Tomolimo

**Comment by shahmilan34** [comment] 2018-08-03 13:21
hi @tomolimo ,
I am also facing same issue
I am not able to see change log and dynaform info in process case
I am not able to find my groups in permissions tab to grant permssions, I also tried giving permissions to a user but still he is not able to see dynaform and change log.

**Comment by tomolimo** [comment] 2018-08-03 15:02
Hello @shahmilan34 
Could you have a look in the GLPI logs and in the PM server logs (by default in PM server, there is no logs, so you may be first set them and do a retest)?
Thank you,
Regards,
Tomolimo

**Comment by shahmilan34** [comment] 2018-08-14 13:05
There are no errors getting logged in glpi errors or apache error log.
How to set processmaker logs?

Kindly suggest

**Comment by tomolimo** [comment] 2018-08-14 13:11
You should find the PM server PHP error log here:
Go to PHP information like shown below, then search for 'error' string and you should get the value of the `error_log` PHP variable which gives the pathfilename of the error log.
![image](https://user-images.githubusercontent.com/7569958/44093463-ebb2ce4e-9fd3-11e8-847c-a2649325aede.png)

If this is empty then set a value to this PHP  variable and then redo your tests.

Thank you
regards,
Tomolimo

**Comment by shahmilan34** [comment] 2018-08-14 13:57
After setting log files also there are no errors
![error_log_path](https://user-images.githubusercontent.com/31683819/44096034-e2558e62-9ff7-11e8-886c-578c082e1086.png)

I tried setting permissions to single user but still that user is not able to see change log and dynaform

**Comment by tomolimo** [comment] 2018-08-14 15:19
Hello @shahmilan34 
Did you check this: https://github.com/tomolimo/processmaker/wiki/How-to-view-the-%27Change-log%27-and-the-%27Dynaforms%27?
Regards,
Tomolimo

**Comment by shahmilan34** [comment] 2018-08-15 09:03
Yes, I did.
that's the problem, no group is getting displayed in permissions's 'User or group field'
and even if i set permission to single user, he is not able to view change log and dyanforms

**Comment by tomolimo** [comment] 2018-08-15 13:35
Did you try to create a new group in PM server and to add some people in it?
And then did you try to add this new group to the authorized group of your process?

**Comment by shahmilan34** [comment] 2018-08-16 09:16
Yes, I did try making groups in PM and assigning users to it but still that groups doesn't show up in Permisssions

**Comment by tomolimo** [comment] 2018-08-16 09:37
Could you please send me your process?
I'll try to do this in my pm server.

**Comment by shahmilan34** [comment] 2018-08-16 10:10
Actually I tried it in various processes and with different processmaker-servers too.
so I think its not related to any specific process.
I also tried with new version of processmaker-server i.e. RE 1.9

**Comment by tomolimo** [comment] 2018-08-16 10:25
Did you try this with the standard PM server? I mean the one from Colosa?

**Comment by shahmilan34** [comment] 2018-08-16 11:49
Same, I am not able to understand where the problem is and I also tried with original processmaker from colosa
I also reported this issue on processmaker forum [issue](https://forum.processmaker.com/viewtopic.php?f=41&t=730754)

**Comment by tomolimo** [comment] 2018-08-16 12:06
I can propose to connect to your pc and PM server to try to debug this issue, would you like to?

**Comment by tomolimo** [comment] 2018-08-17 08:14
Hello @shahmilan34 
What about my proposal?
I can connect to your system with Teamviewer or Jitsi.
Here is my professional email address: olivier.moron@araymond.com
Regards,
Tomolimo

**Comment by shahmilan34** [comment] 2018-08-17 09:36
Yeah sure.
Can we connect on Tuesday?

**Comment by tomolimo** [comment] 2018-08-17 09:43
let's say Tuesday 20:30 UTC+2, if OK for you. And if something is not OK, I'll post

**Comment by shahmilan34** [comment] 2018-08-17 10:11
20:30 UTC+2 is 12 AM IST for me, so can we make it early somewhere like 12.30 UTC 00:00

**Comment by tomolimo** [comment] 2018-08-17 12:30
Could you use my professionnal email address to conclude this meeting?

**Comment by tomolimo** [comment] 2018-08-21 13:25
Hello @shahmilan34, @alogez 
Found the root cause: the sql_mode was not respecting the PM server requirements: https://github.com/tomolimo/processmaker-server/wiki/PHP-and-MySQL-compatibility and there: https://wiki.processmaker.com/3.0/ProcessMaker_Installation_Requirements#Software_Requirements
After setting this sql_mode to an empty string, it works :smiley: 
Thank you,
Regards,
Tomolimo

**Closed by tomolimo** 2018-08-21 13:25 UTC

**Comment by rohit-ambre-uno** [comment] 2018-08-21 13:41
Yeah.
It worked.
Thank you for taking out time to connect to my servers. Really appreciated.
