### ISSUE TITLE
Problem with GLPI_DATA

### ISSUE THREAD

**Issue by jorge-madrigal** [tomolimo/processmaker#167] opened 2023-11-10 19:35 UTC
Hello Tomolimo:

Your plugin is fantastic. we have used version 3.6 and we are migrating the entire system.

I have migrated the plugin and processmaker to the latest version.

I have a problem with GLPI_DATA.
When I go to finish the first task of the Processmaker process, I click the btnGLPISendRequestbutton.
 I have the next mistake:

Uncaught ReferenceError: GLPI_DATA is not defined
    at case_onload (VM773 glpi.js:357:21)

![image](https://github.com/tomolimo/processmaker/assets/66475507/7a3c1877-ad67-4341-876a-a66e50e10d1b)

![image](https://github.com/tomolimo/processmaker/assets/66475507/c09ca715-2f9a-4b28-aa71-09469c5aad11)

Any ideas?

In the first form of the process task, I have a warning that I don't know if it can influence postmessage

![image](https://github.com/tomolimo/processmaker/assets/66475507/1bd1366d-2208-4628-b2a8-b1a92ac00420)
Thank you

**Comment by tomolimo** [comment] 2023-11-13 07:29
Hello @jorge-madrigal 
Could you post a screenshot of the plugin configuration form? 
It's in Setup > General > ProcessMaker
Could you post a screenshot of GLPI configuration?
It's in Setup > General > General Setup
Thank you,
Regards,
Tomolimo

**Comment by jorge-madrigal** [comment] 2023-11-13 09:11
Hello @tomolimo 
 
Here you have my configuration:
![image](https://github.com/tomolimo/processmaker/assets/66475507/13a2bf21-d538-4758-88d5-7e11d9a2b868)

![image](https://github.com/tomolimo/processmaker/assets/66475507/8fb0c498-f8a8-4346-8880-8695dab1fe33)

![image](https://github.com/tomolimo/processmaker/assets/66475507/b5929899-e567-4ca8-beb8-bf62c16d56ea)

![image](https://github.com/tomolimo/processmaker/assets/66475507/a4fa677c-3bb9-40e7-a551-d81c7845944c)

Thank you

**Comment by tomolimo** [comment] 2023-11-13 09:25
Hello @jorge-madrigal,

I think the root cause of the issue is that GLPI defined URL and GLPI used URL are not the same:
The GLPI defined URL is 
![image](https://github.com/tomolimo/processmaker/assets/7569958/db52d984-7d23-45d2-b634-c618b6f3d90b)
And you are really using 
![image](https://github.com/tomolimo/processmaker/assets/7569958/9f690e3a-dd5e-472b-a021-afeaa162d70b)
You MUST use the GLPI defined URL (or you MUST change the GLPI URL), but bith MUST be the same.

Thank you,
Regards,
Tomolimo

**Comment by jorge-madrigal** [comment] 2023-11-13 10:19
Hello @tomolimo 

The first warning regarding pm_glpi has disappeared. I change GLPI_Ul.
But the GLPI_DATA error keeps appearing.

![image](https://github.com/tomolimo/processmaker/assets/66475507/d3d13bf9-82d5-4b5c-8c6c-f4d39da9ac84)

Thank you
Jorge

**Comment by tomolimo** [comment] 2023-11-13 10:36
Hello @jorge-madrigal 
Could you post a screen copy of the previous dynaform from the dynaform editor?
Like this one?
![image](https://github.com/tomolimo/processmaker/assets/7569958/caa90319-41e9-4895-a65c-68368822b1c6)
Thank you,
Regards,
Tomolimo

**Comment by jorge-madrigal** [comment] 2023-11-13 11:15
Hello @tomolimo :

This is de form:
![image](https://github.com/tomolimo/processmaker/assets/66475507/e5ba21ce-81ea-4978-a915-6b7d9933023a)

The process was working fine with version 3.6 of the plugin and processmaker.

I have been looking for the definition of GLPI_DATA in the code of the processmaker plugin and the processmaker server, and I cannot find it.

Where is the variable defined?

Thanks

**Comment by jorge-madrigal** [comment] 2023-11-13 11:36
Hello @tomolino:

For more information: Another thing is that the first task of the process has more than one form.

The first task has 3 forms. There are 3 steps. The last form has the submit btnGLPISendRequest

**Comment by jorge-madrigal** [comment] 2023-11-13 12:17
Hello @tomolimo:

I think I know where the problem is.

As you said, the task has 3 steps. The first is a data form. In that first step there is data in GLPI_DATA. Look at the image:

![image](https://github.com/tomolimo/processmaker/assets/66475507/0808c7b7-0831-47be-887c-d83cc2283986)

I Resume debugger->

![image](https://github.com/tomolimo/processmaker/assets/66475507/bf1142af-5935-4478-a109-19132b3f0b46)

I resume debugger and I enter the data in the form and press next step

In this moment, GLPI_DATA is empty or undefined.

I think GLPI_DATA data is lost when there are multiple steps in the same task.

Thank you

**Comment by tomolimo** [comment] 2023-11-13 13:19
Hello @jorge-madrigal 
I made tests with processes in which there are several steps in one task...
I'll need your process to debug that...
Could you post the pmx file on my Discord account (it's Tomolimo), so that it'll remain private?
Thank you,
Regards,
Tomlimo

**Comment by jorge-madrigal** [comment] 2023-11-13 15:29
Hello 
@tomolimo:
 I would like to send you my process, but it is complicated. Additionally, it uses external databases that you do not have.

I am going to review the steps and try to simplify the task to verify that the error is not from the task itself.

I also use a digital signature script, I am going to check that this script is not the problem.

Give me a day or 2 to research my own task.

Thank you.
Jorge,

**Comment by tomolimo** [comment] 2023-11-14 07:35
Hello @jorge-madrigal 
Thank you,
Regards,
Tomolimo

**Comment by jorge-madrigal** [comment] 2023-11-14 13:46
Hello @tomolimo 

Creo que el problema es de la propia tarea inicial del proceso.

I think the problem is with the initial task of the process itself.

To check this I have created a process with only one task. This task has 2 steps. When I press the btnGLPISendRequest button it does nothing. I have reviewed the code and it remains in (cases.js file):
 myform.requestSubmit(button.length ? button[0] : undefined);

The button finds it but does not validate the form.

A window appears indicating loading...


Do you know any reason why this could happen?

Thank you,
Regards,
Jorge Madrigal

**Comment by tomolimo** [comment] 2023-11-14 15:45
Hello @jorge-madrigal 
In order to be able to help you, I need to have your pmx and the configuration of the process itself in GLPI.
Thank you,
Regards,
Tomolimo

**Comment by jorge-madrigal** [comment] 2023-11-15 09:34
Hello @tomolimo:
I have simplified everything to the maximum.

GLPI, version 10.0.10
Processmaker plugin 5.0.1
GLPI Server: Windows with xampp
Server processmaker version 3.3.0 RE 2.0 Linux

Process= Tutorial.

Everything works until submit. At that moment Loading... appears and does not end.

The process is created in processmaker, but the first task does not finish.

[Tutorial.json](https://github.com/tomolimo/processmaker/files/13362782/Tutorial.json)


Do you have an example that works so I can test it?
Thank you

Jorge Madrigal

**Comment by tomolimo** [comment] 2023-11-15 12:04
Hello @jorge-madrigal 
The json file is the export of the dynaform, not the export of the process which is a PMX file...
Sorry all the examples I have can't be published, only the card sample is public.
But I can try to do a card sample with several steps per tasks.
thank you
regards,
Tomolimo

**Comment by tomolimo** [comment] 2023-11-15 12:58
Hello @jorge-madrigal
The bpmn file is the export of the map of the project, not the export of the process which is a PMX file...
Thank you,
Regards,
Tomolimo

**Comment by jorge-madrigal** [comment] 2023-11-15 13:10
Hello @tomolimo:

I'm sorry. I haven't come today but it seems my brain isn't right.
I hope I get it right this time.

[Prueba-1.zip](https://github.com/tomolimo/processmaker/files/13365054/Prueba-1.zip)

Thank you

Jorge

**Comment by tomolimo** [comment] 2023-11-15 13:52
Hello @jorge-madrigal 
I've successfully imported the process, and I'm going to test it, and I'll keep you informed
thank you,
Regards,
Tomolimo

**Comment by jorge-madrigal** [comment] 2023-11-15 18:37
Hello @tomolimo:

Sorry.

To have more clues. I have tried the example process: Credit Card. I have loaded it into processmaker successfully.
I have tried and the same thing happens, the first task does not finish and the loading icon appears...

First I select the category (CARD CREDIT):
![image](https://github.com/tomolimo/processmaker/assets/66475507/b504415d-48d5-42d5-af09-7eb1f0f42b5a)

The first form appears. I fill it out and press submit
![image](https://github.com/tomolimo/processmaker/assets/66475507/37aea6b7-dd0b-47ed-8e41-e6cabebcd1a2)

When I press submit, appears this..

![image](https://github.com/tomolimo/processmaker/assets/66475507/469a9e6b-a3e2-48fa-b25f-8fe49ac5a091)

The form disappears (as expected), but in processmaker it does not jump to the second task and the GLPI does not create the ticket
![image](https://github.com/tomolimo/processmaker/assets/66475507/f00d0fb8-be6e-49e4-b445-08feccb04889)

Thank you very much for your patience
Jorge Madrigal

**Comment by tomolimo** [comment] 2023-11-16 08:30
Hello @jorge-madrigal 
I've not yet test your process, but I've 2 ideas/questions:
1. Which browser are you using? Which version?
2. Could it be possible for you to do a test using a GLPI with direct URL (I mean without any path in URL)? I can see that GLPI is relocated under a directory (= https://helpdesk.diputaciondevalladolid.es/glpi/public). Could you change your config to be able to use https://helpdesk.diputaciondevalladolid.es/glpi/public?
Thank you,
Regards,
Tomolimo

**Comment by jorge-madrigal** [comment] 2023-11-16 09:35
Hello @tomolimo:

1.- I do the tests with Chrome (version 119.0.6045.159), to see the debugger interruptions. I have tried in Edge (version 119.0.2151.58), with Firefox (119.0.1) and it also fails in all of them.

2.- I'm doing it as you say. For the latest tests, I have used a local GLPI (10.0.10). The url is unique, it has no added paths. The url is jorge.diputaciondevalladolid.es. Just that route. And the failures remain.

![image](https://github.com/tomolimo/processmaker/assets/66475507/e20e4638-623e-4323-865b-111390c4181f)

![image](https://github.com/tomolimo/processmaker/assets/66475507/57ef7376-0800-46bc-a69a-63629f70b7b0)

-------------------------------
Other thing:

This issue was created because GLPI DATA being lost. I know the reason.
In my original process, first task has 3 steps. First, a form, second an output file is generated, third the document is viewed in a PDF viewer.

If the second step is other form, the GLPI_DATa isn't lost.

**When the step is a document generated, GLPI_DATA is lost.**

I attach pmx with a very simple example. In the second step GLPI_DATA is lost.
[Prueba2-2.zip](https://github.com/tomolimo/processmaker/files/13375579/Prueba2-2.zip)

Thank you
Regards
Jorge Madrigal

**Comment by tomolimo** [comment] 2023-11-16 10:09
Hello @jorge-madrigal 
I think you found the root cause to this issue: the "output document" generation: I didn't test this use case.
I'll keep you informed
Thank you,
Regards,
Tomolimo

**Comment by jorge-madrigal** [comment] 2023-11-16 10:16
Hello @tomolimo:

I think there are 2 issues:
1.- The output document step causes GLPI_DATA to be lost (The process I have used is inPrueba2-2.zip)

2.- The process Prueba-1.zip. The task is not completed and the ticket is not created.

I can help you with all the tests you want. We use the processmaker plugin and we want to promote it more in our organization. Therefore, I am the first one interested in helping you.

Thank you,
Regards
Jorge Madrigal

**Comment by tomolimo** [comment] 2023-11-20 09:34
Hello @jorge-madrigal,

Second issue is fixed: see in the attached pmx file
[Prueba-1 (2).zip](https://github.com/tomolimo/processmaker/files/13412102/Prueba-1.2.zip)
The issue root cause is that you've used a button instead of a submit button on the second task. A button will not trigger the save dynaform mechanism and therefore the process cannot evoluate. 
Firt issue. I'm going to check it right now.

Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment] 2023-11-20 14:02
Hello again @jorge-madrigal,

Here is a small video to show you that the issue is now fixed (at least on my dev workstation).
https://github.com/tomolimo/processmaker/assets/7569958/6af4eab7-5692-4bb7-8e93-8f377949bf5a
Give me one hour to provide a new release for the PM server 😃 

Thank you
Regards,
Tomolimo

**Comment by tomolimo** [comment] 2023-11-20 16:35
Fixed by https://github.com/tomolimo/processmaker-server/releases/tag/RE-2.1

**Closed by tomolimo** 2023-11-20 16:35 UTC
