### ISSUE TITLE
Task still not synchronise 

### ISSUE THREAD

**Issue by manoel-cristiano** [tomolimo/processmaker#38] opened 2017-12-18 14:32 UTC
Hi Tomolimo, how have you been?

Unfortunately I still have the same problem that I reported days ago in the issue #36 

I followed what you told me before, but when I try to synchronise nothing happen. 

GLPI version. 9.1.6
Processmaker version. 3.0.1.8-community

![screen shot 2017-12-18 at 11 52 38 am](https://user-images.githubusercontent.com/25938162/34111012-85cd4ec4-e3ef-11e7-8f93-694ca0ab05dc.png)
![screen shot 2017-12-18 at 11 52 52 am](https://user-images.githubusercontent.com/25938162/34111013-85f1a706-e3ef-11e7-8c04-fafc26eb1bc1.png)
![screen shot 2017-12-18 at 11 53 17 am](https://user-images.githubusercontent.com/25938162/34111015-8613f75c-e3ef-11e7-905e-80051680e2b6.png)
![screen shot 2017-12-18 at 11 54 24 am](https://user-images.githubusercontent.com/25938162/34111016-863d929c-e3ef-11e7-9d77-75942c7f89d9.png)
![screen shot 2017-12-18 at 11 54 36 am](https://user-images.githubusercontent.com/25938162/34111017-865f553a-e3ef-11e7-9985-11f438496fcb.png)
![screen shot 2017-12-18 at 11 54 45 am](https://user-images.githubusercontent.com/25938162/34111018-8684f9de-e3ef-11e7-95de-ee5d2d774ac9.png)

**Comment by tomolimo** [comment] 2017-12-18 15:02
Hello
I'm not in front of my computer, but I can try to help you. 
When you did the PM server installation, did the install procedure asked you about one or three databases? 
Regards 
Tomolimo

**Comment by manoel-cristiano** [comment] 2017-12-18 15:55
It just created one database.

**Comment by tomolimo** [comment] 2017-12-18 16:34
Could you give me a screen shot of the wf_workflow database?
If possible with php_mysql?
I would like to have the table list. 
Thank you

**Comment by tomolimo** [comment] 2017-12-18 17:26
Oups, sorry I was speaking about phpmyadmin or any application that can give a list of tables, like following:

TABLE_NAMES
---
| Tables_in_wf_workflow | 
| --- | 
| abe_configuration | 
| abe_requests | 
| abe_responses | 
| additional_tables | 
| addons_manager | 
| addons_store | 
| app_assign_self_service_value | 
| app_cache_view | 
| app_delay | 
| app_delegation | 
| app_document | 
| app_event | 
| app_folder | 
| app_history | 
| app_message | 
| app_notes | 
| app_owner | 
| app_sequence | 
| app_solr_queue | 
| app_thread | 
| app_timeout_action_executed | 
| application | 
| backup_dynaform | 
| bpmn_activity | 
| bpmn_artifact | 
| bpmn_bound | 
| bpmn_data | 
| bpmn_diagram | 
| bpmn_documentation | 
| bpmn_event | 
| bpmn_extension | 
| bpmn_flow | 
| bpmn_gateway | 
| bpmn_lane | 
| bpmn_laneset | 
| bpmn_participant | 
| bpmn_process | 
| bpmn_project | 
| calendar_assignments | 
| calendar_business_hours | 
| calendar_definition | 
| calendar_holidays | 
| case_consolidated | 
| case_scheduler | 
| case_tracker | 
| case_tracker_object | 
| catalog | 
| configuration | 
| content | 
| dashboard | 
| dashboard_das_ind | 
| dashboard_indicator | 
| dashlet | 
| dashlet_instance | 
| db_source | 
| department | 
| dim_time_complete | 
| dim_time_delegate | 
| dynaform | 
| element_task_relation | 
| email_event | 
| email_server | 
| event | 
| field_condition | 
| fields | 
| gateway | 
| gmail_relabeling | 
| group_user | 
| groupwf | 
| holiday | 
| input_document | 
| iso_country | 
| iso_location | 
| iso_subdivision | 
| language | 
| lexico | 
| license_manager | 
| list_canceled | 
| list_completed | 
| list_inbox | 
| list_my_inbox | 
| list_participated_history | 
| list_participated_last | 
| list_paused | 
| list_unassigned | 
| list_unassigned_group | 
| log_cases_scheduler | 
| login_log | 
| message_application | 
| message_event_definition | 
| message_event_relation | 
| message_type | 
| message_type_variable | 
| notification_device | 
| oauth_access_tokens | 
| oauth_authorization_codes | 
| oauth_clients | 
| oauth_refresh_tokens | 
| oauth_scopes | 
| object_permission | 
| output_document | 
| pmoauth_user_access_tokens | 
| pro_reporting | 
| process | 
| process_category | 
| process_files | 
| process_owner | 
| process_user | 
| process_variables | 
| rbac_authentication_source | 
| rbac_permissions | 
| rbac_roles | 
| rbac_roles_permissions | 
| rbac_systems | 
| rbac_users | 
| rbac_users_roles | 
| report_table | 
| report_var | 
| route | 
| script_task | 
| sequences | 
| session | 
| session_storage | 
| shadow_table | 
| stage | 
| step | 
| step_supervisor | 
| step_trigger | 
| sub_application | 
| sub_process | 
| swimlanes_elements | 
| task | 
| task_user | 
| timer_event | 
| translation | 
| triggers | 
| users | 
| users_properties | 
| usr_reporting | 
| web_entry | 
| web_entry_event |

**Comment by manoel-cristiano** [comment] 2017-12-18 17:48
Follow the screen shots.
![screen shot 2017-12-18 at 3 47 25 pm](https://user-images.githubusercontent.com/25938162/34119866-d03bcba0-e40a-11e7-80b8-fe97ab45bd83.png)
![screen shot 2017-12-18 at 3 48 06 pm](https://user-images.githubusercontent.com/25938162/34119867-d0934a92-e40a-11e7-8b68-75c21c87440d.png)
![screen shot 2017-12-18 at 3 48 23 pm](https://user-images.githubusercontent.com/25938162/34119868-d0b41cae-e40a-11e7-9137-70dae324213a.png)
![screen shot 2017-12-18 at 3 48 39 pm](https://user-images.githubusercontent.com/25938162/34119869-d0d7ce1a-e40a-11e7-916e-0dead5da8e04.png)
![screen shot 2017-12-18 at 3 48 53 pm](https://user-images.githubusercontent.com/25938162/34119871-d0f72d8c-e40a-11e7-97e0-bf2bea98e760.png)

**Comment by tomolimo** [comment] 2017-12-18 17:49
Thank you,
I think I understand the trouble.
I'll give you a fix ASAP.
Regards,
Tomolimo

**Comment by tomolimo** [comment] 2017-12-18 17:56
Could you remind me the processmaker plugin version?

**Comment by manoel-cristiano** [comment] 2017-12-18 17:58
The plugin version is 3.1.6.

**Comment by tomolimo** [comment] 2017-12-18 18:01
And you still have the same error in the logs?

**Comment by manoel-cristiano** [comment] 2017-12-18 18:38
Follow my config.

![screen shot 2017-12-18 at 4 39 56 pm](https://user-images.githubusercontent.com/25938162/34121913-d108fcea-e411-11e7-9f32-87529d921487.png)

**Comment by tomolimo** [comment] 2017-12-18 20:56
What are the rights of your 'handson' user in mySQL?

**Comment by manoel-cristiano** [comment] 2017-12-19 11:54
The user handson has full rights on mysql. 
Sorry for the delay to answer.

**Comment by tomolimo** [comment] 2018-01-03 13:25
Hello,
Happy new year,

Could you try with latest version of the plugin?

Thank you
regards,
Tomolimo

**Comment by sosfc** [comment] 2018-01-20 13:06
Hi Tomolimo
I have the same problem with last version of plugin (3.2.1)
GLPI 9.1.2
PHP 5.6.33
Processmaker version. 3.0.1.8-community

I followed your tuto1 and it works fine (I can see the process, the users are synchronized and so are the groups)
When I click on "Synchronize tasks list", I have a blank page

Thanks for your help
Regards,
Fernand

**Comment by tomolimo** [comment] 2018-01-24 14:38
Hello
You may have a trouble with the Intl PHP module which can be missing.
Could you check that you have this module? And that it is activated?
You may do this command: "php -m" which gives the module list.
Thank you
regards,
Tomolimo

**Comment by sosfc** [comment] 2018-01-25 10:36
Hello,
There is the result of php -m

[PHP Modules]
apc
apcu
bcmath
bz2
calendar
Core
ctype
curl
date
dba
dom
ereg
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
imagick
imap
intl
json
ldap
libxml
mbstring
mcrypt
mhash
mysql
mysqli
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
snmp
soap
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
The international module seems to be activated
Thanks

**Comment by tomolimo** [comment] 2018-01-26 07:44
Hello @sosfc and @manoel-cristiano,
Could you also check that GLPI server "knows" the IP address of the PM server?
To check this you must try to ping PM server from the GLPI server within a terminal session open on the GLPI server.
If not, you must add the IP address of ProcessMaker server in the "hosts" file of the GLPI server. Usually the hosts file is there on Linux systems: /etc/, and in C:\Windows\System32\drivers\etc\ on windows systems.
Thank you,
Tomolimo

**Comment by sosfc** [comment] 2018-01-26 10:59
Hello Tomilimo
The ping works for me
Thanks

**Comment by tomolimo** [comment] 2018-01-26 13:33
Hello @manoel-cristiano, @sosfc 
Could you test with the latest release of the server 3.0.1.8-RE-1.8 and of the plugin 3.2.3?
Thank you
Regards,
Tomolimo

**Comment by sosfc** [comment] 2018-01-27 12:57
Hello,
I have tried new plugin
I don't have any blank page, but no tasks are synchronized
which log may I send you to help you ?
Thanks
Fernand

**Comment by tomolimo** [comment] 2018-01-29 07:35
Hello,
For GLPI, the logs are in glpi_installation_folder/files/_log/, there you should find PHP logs of GLPI, and SQL logs.
For PM, it depends on how you have installed your PHP. to check, you must go to the following page in PM server and search for error_log in the php_info() 'master value' column like shown below:
![image](https://user-images.githubusercontent.com/7569958/35498460-aa81da6e-04ce-11e8-8dee-9d1e875813e5.png)
Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment] 2018-01-29 07:52
Hello @sosfc 

> I have tried new plugin

Did you also installed the new PM server version 3.0.1.8-RE-1.8?
Tomolimo

**Comment by sosfc** [comment] 2018-01-29 12:25
Hi Tomolimo,
My PM version is 3.0.1.8-commutity
My errror_log variable is empty (I did a standard installation with debian distro)
Attached is the php-error from my glpi server
Fernand
Thanks
[php-errors.log](https://github.com/tomolimo/processmaker/files/1673502/php-errors.log)

**Comment by tomolimo** [comment] 2018-01-29 12:40
Hello @sosfc ,
As in your logs it says:

> 2018-01-29 08:21:04 [2@srvweb2]
>   *** PHP Notice(8): Undefined property: stdClass::$status
>   Backtrace :
>   ...ns/processmaker/inc/processmaker.class.php:1116 
>   :                                                  PluginProcessmakerProcessmaker::cronPMUsers()
>   inc/crontask.class.php:832                         call_user_func()
>   front/crontask.form.php:50                         CronTask::launch()

I fear that you are not using the right release of the PM server. You must use the one I provide: 3.0.1.8-community-RE-1.8 and no other versions! See: https://github.com/tomolimo/processmaker/wiki/Introduction

Could you check here:
![image](https://user-images.githubusercontent.com/7569958/35510569-e101de66-04f8-11e8-80fe-6aed16d09da3.png)

Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment] 2018-01-29 12:44
dear a @sosfc ,

And regarding the error_log which is empty, I advise you to set in the PHP config this PHP setting to point to an existing folder where it must have the right to write. I advise you to use the one of GLPI (glpi_folder/files/_log/php-errors.log), so that in one log file you'll get error for GLPI and PM.

regards,
Tomolimo

**Comment by sosfc** [comment] 2018-02-03 12:34
Hi tomolimo,
I reinstalled pm server with the right version (sorry for this mistake) (php intl activated, php 5.6)
I tried plugin 3.2.1 and 3.2.5 with same result
GLPI 9.1.6
I Have no error on the GLPI side, but some errors on the pm side
Below is the content of my php error_log.log
<?php
/**
 * $Header: /repository/pear/Log/Log/error_log.php,v 1.8 2006/06/29 07:09:21 jon Exp $
 *
 * @version $Revision: 1.8 $
 * @package Log
 */

/**
 * The Log_error_log class is a concrete implementation of the Log abstract
 * class that logs messages using PHP's error_log() function.
 *
 * @author  Jon Parise <jon@php.net>
 * @since   Log 1.7.0
 * @package Log
 *
 * @example error_log.php   Using the error_log handler.
 */
class Log_error_log extends Log
{
    /**
     * The error_log() log type.
     * @var integer
     * @access private
     */
    var $_type = PEAR_LOG_TYPE_SYSTEM;

    /**
     * The type-specific destination value.
     * @var string
     * @access private
     */
    var $_destination = '';

    /**
     * Additional headers to pass to the mail() function when the
     * PEAR_LOG_TYPE_MAIL type is used.
     * @var string
     * @access private
     */
    var $_extra_headers = '';

    /**
     * Constructs a new Log_error_log object.
     *
     * @param string $name     Ignored.
     * @param string $ident    The identity string.
     * @param array  $conf     The configuration array.
     * @param int    $level    Log messages up to and including this level.
     * @access public
     */
    function Log_error_log($name, $ident = '', $conf = array(),
                           $level = PEAR_LOG_DEBUG)
    {
        if(!class_exists('G')){
          $realdocuroot = str_replace( '\\', '/', $_SERVER['DOCUMENT_ROOT'] );
          $docuroot = explode( '/', $realdocuroot );
          array_pop( $docuroot );
          $pathhome = implode( '/', $docuroot ) . '/';
          array_pop( $docuroot );
          $pathTrunk = implode( '/', $docuroot ) . '/';
          require_once($pathTrunk.'gulliver/system/class.g.php');
        }
        $this->_id = G::encryptOld(microtime());
        $this->_type = $name;
        $this->_ident = $ident;
        $this->_mask = Log::UPTO($level);

        if (!empty($conf['destination'])) {
            $this->_destination = $conf['destination'];
        }
        if (!empty($conf['extra_headers'])) {
            $this->_extra_headers = $conf['extra_headers'];
        }
    }

    /**
     * Opens the handler.
     *
     * @access  public
     * @since   Log 1.9.6
     */
    function open()
    {
        $this->_opened = true;
        return true;
    }

    /**
     * Closes the handler.
     *
     * @access  public
     * @since   Log 1.9.6
     */
    function close()
    {
        $this->_opened = false;
        return true;
    }

    /**
     * Logs $message using PHP's error_log() function.  The message is also
     * passed along to any Log_observer instances that are observing this Log.
     *
     * @param mixed  $message   String or object containing the message to log.
     * @param string $priority The priority of the message.  Valid
     *                  values are: PEAR_LOG_EMERG, PEAR_LOG_ALERT,
     *                  PEAR_LOG_CRIT, PEAR_LOG_ERR, PEAR_LOG_WARNING,
     *                  PEAR_LOG_NOTICE, PEAR_LOG_INFO, and PEAR_LOG_DEBUG.
     * @return boolean  True on success or false on failure.
     * @access public
     */
    function log($message, $priority = null)
    {
        /* If a priority hasn't been specified, use the default value. */
        if ($priority === null) {
            $priority = $this->_priority;
        }

        /* Abort early if the priority is above the maximum logging level. */
        if (!$this->_isMasked($priority)) {
            return false;
        }

        /* Extract the string representation of the message. */
        $message = $this->_extractMessage($message);

        $success = error_log($this->_ident . ': ' . $message, $this->_type,
                             $this->_destination, $this->_extra_headers);

        $this->_announce(array('priority' => $priority, 'message' => $message));

        return $success;
    }

}

Hope this helps

**Comment by tomolimo** [comment] 2018-02-05 07:32
Hello @sosfc,
The so-called log error content is in fact the content of a PHP file: _pm_server_folder/gulliver/thirdparty/pear/Log/error_log.php_ and not the content of a log file.

Could you check where the PM server log file is?
To locate it you must look at the PHP running variables like shown here: https://github.com/tomolimo/processmaker/issues/38#issuecomment-361161953

And as you said that it is empty, then could you add in your PHP.ini file the location of the GLPI error log file? So that you'll get all error messages into the same log file.
Then you should be able to clear the log files, and redo a test in order to get errors (if any) related to the test.

Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment] 2018-04-03 07:49
Hello @manoel-cristiano and @sosfc ,
Could you tell me the default language you have defined in GLPI and in PM server?
I think this is root cause of the issue when those languages are different.
Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment] 2018-04-03 07:58
Hello,

Could you copy/paste the following screencopy?

![image](https://user-images.githubusercontent.com/7569958/38236778-85de6b12-3725-11e8-8570-dc1a5ccef7d4.png)

I need to know which languages are installed in PM server.

Thank you,
Regards,
Tomolimo

**Comment by sosfc** [comment] 2018-04-03 10:12
Hello Tomolimo
My default language is French
[pm_language.pdf](https://github.com/tomolimo/processmaker/files/1871077/pm_language.pdf)

**Comment by sosfc** [comment] 2018-04-03 10:20
Here is the GLPI plugin configuration screen
[pm_glpi.pdf](https://github.com/tomolimo/processmaker/files/1871101/pm_glpi.pdf)

**Comment by tomolimo** [comment] 2018-04-03 11:03
Hello
The trouble is coming from the fact that you have installed "fr-FR", and not "fr", see https://github.com/tomolimo/processmaker-server/wiki/Languages

Thank you
Regards,
Tomolimo

**Comment by sosfc** [comment] 2018-04-03 11:23
Hello Tomolimo
Thanks for the fast reply !
The problem is that for version 3.0 there is no fr file (just fr-FR) and when I download the fr file of the "po files" repository, it says "invalid po file format"
Thanks for your help
Regards Fernand

**Comment by tomolimo** [comment] 2018-04-03 11:29
Hello,
You have to change it as explained here https://github.com/tomolimo/processmaker-server/wiki/Languages#localization-internationalization-languages :

1. rename of the file
1. edit of the content header

regards,
Tomolimo

**Comment by sosfc** [comment] 2018-04-03 15:13
You got it !
It works fine
Thanks !
Fernand

**Comment by manoel-cristiano** [comment] 2018-04-03 16:24
Hello,
@tomolimo I gonna chanche my language configuration in GLPI, because I'm using pt-BR. But in process maker I'm using (en international).

**Comment by tomolimo** [comment] 2018-04-04 06:13
Hello @manoel-cristiano 
Could you post here the screen shot of the installed languages in PM server?
Like this:
![image](https://user-images.githubusercontent.com/7569958/38291437-ff323a2e-37df-11e8-8fc8-53a8b35214de.png)
Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment] 2018-07-04 09:07
Hello
As there has been no answer since last post, close this issue.
Feel free to re-open it if you've get news.
Thank you,
Regards,
Tomolimo

**Closed by tomolimo** 2018-07-04 09:07 UTC
Labels: help wanted

**Comment by allanregistos** [comment] 2019-05-04 07:58
Hi, can we revive this thread?

Have the same error, no synchronization of PM tasks in GLPI so I cannot map the GLPI ticket with my PM processes.
Here is the log error of php-errors log:


  Processmaker Plugin:  - User not existing in glpi_plugin_processmaker_users table.
2019-05-04 15:54:07 [7@smpc.steniel.com.ph]
  From PluginProcessmakerProcessmaker::login() in /var/www/glpi/plugins/processmaker/inc/processmaker.class.php line 276
  Processmaker Plugin:  - User not existing in glpi_plugin_processmaker_users table.
2019-05-04 15:54:07 [7@smpc.steniel.com.ph]
  From PluginProcessmakerProcessmaker::login() in /var/www/glpi/plugins/processmaker/inc/processmaker.class.php line 276
  Processmaker Plugin:  - User not existing in glpi_plugin_processmaker_users table.

I followed exactly, the tutorial and got success at the Setup -> General -> Processmaker config:

![image](https://user-images.githubusercontent.com/8325058/57176006-64a8ca80-6e85-11e9-9ec2-4894500bfa21.png)

**Comment by rohit-ambre-uno** [comment] 2019-05-06 04:12
hi @allanregistos ,
have you ran "pmusers" cron job from automatic actions?

from the errors it seems like you have not synced users from glpi to processmaker.

**Comment by allanregistos** [comment] 2019-05-06 05:11
Hi rohit-ambre-uno,
I did not for I do not know that I needed to do that.
For the synchronization of  users, did you mean, matching username and password for both glpi and processmaker or do I have to get a glpi function?

Thanks for responding..
Allan

**Comment by tomolimo** [comment] 2019-05-06 06:14
Hello @allanregistos,
As this issue is closed, could you open a new issue and link it to this one (using a sharp + issue id, like: #38)  if you see that the behavior is the identical?
Thank you
Regards,
Tomolimo
