### ISSUE TITLE
Problem when install

### ISSUE THREAD

**Issue by easjrgrp** [tomolimo/processmaker#2] opened 2015-12-30 16:20 UTC
I have interest in running your plugin, but something wrong happaned when i try to install.

Versions (everything up to date):
CENTOS 7
GLPI: 0.83.8
ProcessMaker: 2.8
ProcessMaker Plugin: 2.4.1

I downloaded the page plugin installed all dependencies, and when I start the installation page of plugins closes and clicking again plugins it appears without being installed, and the option to install appears again, and when I try the same thing happens again . Only ProcessMaker user was created.
What can I do to fix this?

**Comment by tomolimo** [comment] 2016-01-04 07:21
Hello,
Sorry for being long to answer to you (I was in holidays:)).
Could you have a look at log files in glpi/files/_log ?
Did you follow the wiki for ProcessMaker installation and configuration?
Regards,
Tomolimo

**Comment by easjrgrp** [comment] 2016-01-04 13:32
hello,
No problem, we all need some holidays :)).
I followed the wiki for installing and configuring ProcessMaker plugin.
To ease debugging, moved the installation of GLPI and ProcessMaker to XAMPP. both systems are operating without problem but when I run the plugin the same thing happens, creates ProcessMaker user and nothing else.
the log file has the messages:
2015-12-30 14:47
Warning(2): SoapClient::SoapClient(http://localhost//sysworkflow/pt/classic/services/wsdl2): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found

Backtrace :
C:\xampp\htdocs\glpi2\plugins\processmaker\inc\processmaker.class.php:133		SoapClient->SoapClient()
C:\xampp\htdocs\glpi2\plugins\processmaker\inc\processmaker.class.php:211		PluginProcessmakerProcessmaker->openSoap()
C:\xampp\htdocs\glpi2\plugins\processmaker\hook.php:265		PluginProcessmakerProcessmaker->login()
C:\xampp\htdocs\glpi2\inc\plugin.class.php:582		plugin_processmaker_install()
C:\xampp\htdocs\glpi2\front\plugin.php:74		Plugin->install()

2015-12-30 14:47
Warning(2): SoapClient::SoapClient(): I/O warning : failed to load external entity &quot;http://localhost//sysworkflow/pt/classic/services/wsdl2&quot;
Backtrace :
C:\xampp\htdocs\glpi2\plugins\processmaker\inc\processmaker.class.php:133		SoapClient->SoapClient()
C:\xampp\htdocs\glpi2\plugins\processmaker\inc\processmaker.class.php:211		PluginProcessmakerProcessmaker->openSoap()
C:\xampp\htdocs\glpi2\plugins\processmaker\hook.php:265		PluginProcessmakerProcessmaker->login()
C:\xampp\htdocs\glpi2\inc\plugin.class.php:582		plugin_processmaker_install()
C:\xampp\htdocs\glpi2\front\plugin.php:74		Plugin->install()

2015-12-30 14:47
 SoapFault Object
(
    [message:protected] => SOAP-ERROR: Parsing WSDL: Couldn't load from 'http://localhost//sysworkflow/pt/classic/services/wsdl2' : failed to load external entity "http://localhost//sysworkflow/pt/classic/services/wsdl2"

    [string:Exception:private] => 
    [code:protected] => 0
    [file:protected] => C:\xampp\htdocs\glpi2\plugins\processmaker\inc\processmaker.class.php
    [line:protected] => 133
    [trace:Exception:private] => Array
        (
            [0] => Array
                (
                    [file] => C:\xampp\htdocs\glpi2\plugins\processmaker\inc\processmaker.class.php
                    [line] => 133
                    [function] => SoapClient
                    [class] => SoapClient
                    [type] => ->
                    [args] => Array
                        (
                            [0] => http://localhost//sysworkflow/pt/classic/services/wsdl2
                            [1] => Array
                                (
                                    [soap_version] => 2
                                    [compression] => 32
                                )

                        )

                )

            [1] => Array
                (
                    [file] => C:\xampp\htdocs\glpi2\plugins\processmaker\inc\processmaker.class.php
                    [line] => 211
                    [function] => openSoap
                    [class] => PluginProcessmakerProcessmaker
                    [type] => ->
                    [args] => Array
                        (
                        )

                )

            [2] => Array
                (
                    [file] => C:\xampp\htdocs\glpi2\plugins\processmaker\hook.php
                    [line] => 265
                    [function] => login
                    [class] => PluginProcessmakerProcessmaker
                    [type] => ->
                    [args] => Array
                        (
                            [0] => 1
                        )

                )

            [3] => Array
                (
                    [file] => C:\xampp\htdocs\glpi2\inc\plugin.class.php
                    [line] => 582
                    [function] => plugin_processmaker_install
                    [args] => Array
                        (
                        )

                )

            [4] => Array
                (
                    [file] => C:\xampp\htdocs\glpi2\front\plugin.php
                    [line] => 74
                    [function] => install
                    [class] => Plugin
                    [type] => ->
                    [args] => Array
                        (
                            [0] => 2
                        )

                )

        )

    [previous:Exception:private] => 
    [faultstring] => SOAP-ERROR: Parsing WSDL: Couldn't load from 'http://localhost//sysworkflow/pt/classic/services/wsdl2' : failed to load external entity "http://localhost//sysworkflow/pt/classic/services/wsdl2"

    [faultcode] => WSDL
)

2015-12-30 14:47
 Processmaker Plugin: Soap problem (0.000", 7.64Mio)
2015-12-30 14:56
Warning(2): SoapClient::SoapClient(http://localhost//sysworkflow/pt/classic/services/wsdl2): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found

Backtrace :
C:\xampp\htdocs\glpi2\plugins\processmaker\inc\processmaker.class.php:133		SoapClient->SoapClient()
C:\xampp\htdocs\glpi2\plugins\processmaker\inc\processmaker.class.php:211		PluginProcessmakerProcessmaker->openSoap()
C:\xampp\htdocs\glpi2\plugins\processmaker\hook.php:265		PluginProcessmakerProcessmaker->login()
C:\xampp\htdocs\glpi2\inc\plugin.class.php:582		plugin_processmaker_install()
C:\xampp\htdocs\glpi2\front\plugin.php:74		Plugin->install()

2015-12-30 14:56
Warning(2): SoapClient::SoapClient(): I/O warning : failed to load external entity &quot;http://localhost//sysworkflow/pt/classic/services/wsdl2&quot;
Backtrace :
C:\xampp\htdocs\glpi2\plugins\processmaker\inc\processmaker.class.php:133		SoapClient->SoapClient()
C:\xampp\htdocs\glpi2\plugins\processmaker\inc\processmaker.class.php:211		PluginProcessmakerProcessmaker->openSoap()
C:\xampp\htdocs\glpi2\plugins\processmaker\hook.php:265		PluginProcessmakerProcessmaker->login()
C:\xampp\htdocs\glpi2\inc\plugin.class.php:582		plugin_processmaker_install()
C:\xampp\htdocs\glpi2\front\plugin.php:74		Plugin->install()

2015-12-30 14:56
 SoapFault Object
(
    [message:protected] => SOAP-ERROR: Parsing WSDL: Couldn't load from 'http://localhost//sysworkflow/pt/classic/services/wsdl2' : failed to load external entity "http://localhost//sysworkflow/pt/classic/services/wsdl2"

    [string:Exception:private] => 
    [code:protected] => 0
    [file:protected] => C:\xampp\htdocs\glpi2\plugins\processmaker\inc\processmaker.class.php
    [line:protected] => 133
    [trace:Exception:private] => Array
        (
            [0] => Array
                (
                    [file] => C:\xampp\htdocs\glpi2\plugins\processmaker\inc\processmaker.class.php
                    [line] => 133
                    [function] => SoapClient
                    [class] => SoapClient
                    [type] => ->
                    [args] => Array
                        (
                            [0] => http://localhost//sysworkflow/pt/classic/services/wsdl2
                            [1] => Array
                                (
                                    [soap_version] => 2
                                    [compression] => 32
                                )

                        )

                )

            [1] => Array
                (
                    [file] => C:\xampp\htdocs\glpi2\plugins\processmaker\inc\processmaker.class.php
                    [line] => 211
                    [function] => openSoap
                    [class] => PluginProcessmakerProcessmaker
                    [type] => ->
                    [args] => Array
                        (
                        )

                )

            [2] => Array
                (
                    [file] => C:\xampp\htdocs\glpi2\plugins\processmaker\hook.php
                    [line] => 265
                    [function] => login
                    [class] => PluginProcessmakerProcessmaker
                    [type] => ->
                    [args] => Array
                        (
                            [0] => 1
                        )

                )

            [3] => Array
                (
                    [file] => C:\xampp\htdocs\glpi2\inc\plugin.class.php
                    [line] => 582
                    [function] => plugin_processmaker_install
                    [args] => Array
                        (
                        )

                )

            [4] => Array
                (
                    [file] => C:\xampp\htdocs\glpi2\front\plugin.php
                    [line] => 74
                    [function] => install
                    [class] => Plugin
                    [type] => ->
                    [args] => Array
                        (
                            [0] => 2
                        )

                )

        )

    [previous:Exception:private] => 
    [faultstring] => SOAP-ERROR: Parsing WSDL: Couldn't load from 'http://localhost//sysworkflow/pt/classic/services/wsdl2' : failed to load external enti

**Comment by tomolimo** [comment] 2016-01-04 14:21
Ok I see,
Could go to PM admin interface? And could you test web services?
![admin in workflow - windows internet explorer_2016-01-04_15-20-03](https://cloud.githubusercontent.com/assets/7569958/12091361/daa6b178-b2f6-11e5-86d2-1e2fbbc66065.png)

**Comment by tomolimo** [comment] 2016-01-04 14:22
From there you should be able to login to web service, if not then there is a problem deep in PM.
We'll see at that moment

**Comment by tomolimo** [comment] 2016-01-04 14:30
Another way to test could be to copy/paste the URL for the web services into a browser.

Also I can see that the searched URL is http://localhost//sysworkflow/pt/classic/services/wsdl2
Try to delete the second / like: http://localhost/sysworkflow....
For that change in ProcessMaker plugin the URL of ProcessMaker server you have probably set this / at the end of the server URL....

**Comment by tomolimo** [comment] 2016-01-04 14:34
For the test in the browser you should get something like following:

    <?xml version="1.0" encoding="UTF-8"?>
       definitions xmlns="http://schemas.xmlsoap.org/wsdl/"  xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xs0="http://www.processmaker.com" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" targetNamespace="http://www.processmaker.com">-<types>-<xs:schema targetNamespace="http://www.processmaker.com" elementFormDefault="qualified">-<xs:element name="login">-<xs:complexType>-<xs:sequence><xs:element name="userid" type="xs:string"/><xs:element name="password" type="xs:string"/></xs:sequence></xs:complexType></xs:element>-<xs:element name="loginResponse">-<xs:complexType>-<xs:sequence><xs:element name="status_code"  type="xs:integer"/><xs:element name="message" type="xs:string

**Comment by easjrgrp** [comment] 2016-01-04 14:36
![pm](https://cloud.githubusercontent.com/assets/16491141/12091700/574f499e-b2d7-11e5-91db-4d99293f6da5.png)

**Comment by tomolimo** [comment] 2016-01-04 14:37
Perfect, then the problem is due to the double // in the URL

**Comment by easjrgrp** [comment] 2016-01-04 14:42
I use the URL: processmaker.dev and not localhost, it can lead to this problem?

**Comment by tomolimo** [comment] 2016-01-04 14:43
beware that it has to be "http://processmaker.dev" : no '/' at the end (there is a bug if you add a '/' at the end)

**Comment by easjrgrp** [comment] 2016-01-04 14:47
![pm2](https://cloud.githubusercontent.com/assets/16491141/12091931/e12efa46-b2d8-11e5-9a3a-cddd98e3accb.png)

**Comment by easjrgrp** [comment] 2016-01-04 14:47
![pm3](https://cloud.githubusercontent.com/assets/16491141/12091944/f3559e3c-b2d8-11e5-8f16-4c381461039a.png)

**Comment by easjrgrp** [comment] 2016-01-04 14:49
If I use http: //processmaker.dev/.... works!, but if you use http: // localhost/... not;

**Comment by tomolimo** [comment] 2016-01-04 14:51
then you have a web server setup problem, as localhost "should" work too.
But for the plugin, you may use "http://processmaker.dev"

**Comment by tomolimo** [comment] 2016-01-05 12:36
Hello,
Did you retry with the right URL?
regards,
Tomolimo

**Comment by easjrgrp** [comment] 2016-01-05 18:03
hello,
not yet, many problems in the network...
I will try as soon as possible, maybe tomorrow will be possible continue the test. But i have a doubt, where can i setup the correct URL in the plugin?

regards, 
Everaldo

**Comment by tomolimo** [comment] 2016-01-06 06:27
Hello,
Here you are:
![glpi - setup - windows internet explorer_2016-01-06_07-25-38](https://cloud.githubusercontent.com/assets/7569958/12136318/e0aa69b0-b446-11e5-888a-1d623f30de59.png)
regards,
Tomolio

**Comment by easjrgrp** [comment] 2016-01-06 12:47
hello,
unfortunately in my glpi not exist this option !?

![general](https://cloud.githubusercontent.com/assets/16491141/12142891/74120b96-b45a-11e5-8798-d2b1782a5d5d.png)

regards,
Everaldo

**Comment by tomolimo** [comment] 2016-01-06 12:48
Did you enable ProcessMaker plugin?

**Comment by easjrgrp** [comment] 2016-01-06 12:48
Plugins...

![plugins](https://cloud.githubusercontent.com/assets/16491141/12142916/a261a8e4-b45a-11e5-9bf0-2a3862e492c8.png)

**Comment by easjrgrp** [comment] 2016-01-06 12:50
When a click INSTALL...

![plugins2](https://cloud.githubusercontent.com/assets/16491141/12142940/dead4222-b45a-11e5-8a15-3b526492e230.png)

**Comment by tomolimo** [comment] 2016-01-06 12:57
Yes, I can see this is a bug in the install procedure...
The default URL is "http://localhost=/" and cannot be changed by interface (this behavior has been changed in latest version which will be for GLPI 0.90).

Let's try to fix this for you
Do you have acces to a tool that allow to edit mySQL table records (like phpmyadmin, or else)?
If yes, we need to change the URL in the GLPI database in table "glpi_plugin_processmaker_configs"
Could you set the field 'pm_server_URL'  to "http://localhost" instead of "http://localhost/"?
regards,
Tomolimo

**Comment by tomolimo** [comment] 2016-01-06 13:07
Then we may have something else to do: the plugin is using a special account to get administrator rights over ProcessMaker server.
And I forgot to set this in the wiki :(
So we'll need to do some database  modifications (this has been fixed in latest version of the plugin that will be available for GLPI 0.90).
Tell me when you are ready

**Comment by easjrgrp** [comment] 2016-01-06 14:03
It worked !

![plugins4](https://cloud.githubusercontent.com/assets/16491141/12144227/12d2bbfe-b465-11e5-94c6-aa19e7e9dd47.png)

![plugins3](https://cloud.githubusercontent.com/assets/16491141/12144231/193702fc-b465-11e5-81cb-b6e7ff7f5e70.png)

**Comment by tomolimo** [comment] 2016-01-06 14:12
Yes, but you can see the group for glpi users is empty....it means that plugin cannot log into PM server with admin rights.
For that you have to first create in PM a new user named 'glpi' with a special password (that's really the problem: I've forgotten the password).
Let's see:
![admin in workflow - windows internet explorer_2016-01-06_15-08-31](https://cloud.githubusercontent.com/assets/7569958/12144385/904c90f6-b487-11e5-9605-23b1d3285e70.png)

![admin in workflow - windows internet explorer_2016-01-06_15-10-34](https://cloud.githubusercontent.com/assets/7569958/12144421/d184f0a4-b487-11e5-8bbe-65f62d166c8f.png)

Set any password you want for the 'glpi' user, we'll change it in the database anyway.

**Comment by tomolimo** [comment] 2016-01-06 14:19
After user has been created, go to your preferred tool for editing mySQL tables,
and connect to your server to the following database: 'wf_workflow' and go to table 'user', select the record for user 'glpi' (you may query on the 'USR_USERNAME' field) and replace the current 'USR_PASWWORD' value by 2b0a4830b22f1f5ef5f8c239f9c8f07e 
Do the same in the table 'rbac_users' (same fields).

After that the special GLPI user (named 'glpi') has an admin access to PM server and it can add groups, and users from GLPI.

So to do this: go to GLPI plugin list: uninstall the PM plugin, and install it again: it should create at least the default group 'GLPI Requester' into PM server.

**Comment by easjrgrp** [comment] 2016-01-06 14:27
Done !

![pm](https://cloud.githubusercontent.com/assets/16491141/12144707/65c5bb38-b468-11e5-9346-dd6800545c0e.png)

**Comment by tomolimo** [comment] 2016-01-06 14:28
then if you  uninstall and re-install PM plugin you should be able to see all GLPI users in this group.

**Comment by tomolimo** [comment] 2016-01-06 14:30
and this group will be shown in the PM plugin parameters as the one used for GLPI users.

**Comment by tomolimo** [comment] 2016-01-06 14:31
oups, sorry to fill in this group you must activate the cron task "pmusers" in GLPI, as it is no longer done during installation but by the cron task

**Comment by tomolimo** [comment] 2016-01-06 14:37
![glpi - automatic actions - windows internet explorer_2016-01-06_15-36-26](https://cloud.githubusercontent.com/assets/7569958/12144946/59e13c2a-b48b-11e5-89a1-a2cf5cc1d056.png)

**Comment by tomolimo** [comment] 2016-01-06 14:38
you may force execution of the cron:
![glpi - automatic actions - windows internet explorer_2016-01-06_15-37-35](https://cloud.githubusercontent.com/assets/7569958/12144969/892adedc-b48b-11e5-9f5c-58f79b991f31.png)

**Comment by tomolimo** [comment] 2016-01-06 14:39
After that I'll explain how groups are synchronized, just tell me when users are in the 'GLPI Requesters' group.

**Comment by easjrgrp** [comment] 2016-01-06 14:41
Done !

![pm2](https://cloud.githubusercontent.com/assets/16491141/12145009/55bac452-b46a-11e5-9e2e-d805e50b5230.png)

**Comment by tomolimo** [comment] 2016-01-06 14:51
Perfect!

So as you know GLPI can't manage groups assigned to ticket task, to workaround this I've created a notion of pseudo-groups that are in fact GLPI users with an email that is really a distribution list.
And this is mandatory as PM server manages groups assigned to process tasks.
So to be clear if you need groups to be assigned to tasks (this permits collective assignments of tasks to groups instead of only one person) you need to prefix GLPI groups by a * (a star), and to create GLPI users with the same name than the groups you want to synchronize into PM server.

Let's take an example: in GLPI create a group: '*Technicians' (without quotes) , put into this group GLPI users (like glpi and tech). Create a pseudo-group: create a user with the very same '*Technicians' (without quotes) set to pseud-group a valid email address (which normally should be a distribution list, but for test you may choose any).

then you redo the 'execute' of the pmusers cron task, you should be able to get a new group in PM server (named '*Technicians') along with the users inside this new group.

**Comment by easjrgrp** [comment] 2016-01-06 15:14
I created, in GLPI, the group with users, then run again the pmuser cron. In PM the group was created, but without users.

![glpi-grp](https://cloud.githubusercontent.com/assets/16491141/12145789/07655bbe-b46f-11e5-92a3-941b41e924d9.png)

![pm3](https://cloud.githubusercontent.com/assets/16491141/12145797/0fede9d6-b46f-11e5-80cb-71fc9ca1dccb.png)

**Comment by easjrgrp** [comment] 2016-01-06 15:20
So, in PM, I can add manually the users in the group, it is not a problem.

**Comment by tomolimo** [comment] 2016-01-06 15:21
in the group name the * (star) prefix is missing: names for groups and pseud-groups must match.
change group name and redo the execution of the pmusers cron task

**Comment by easjrgrp** [comment] 2016-01-06 15:55
exactly.
It worked perfectly !

**Comment by tomolimo** [comment] 2016-01-06 15:56
users have been added to PM group?

**Comment by easjrgrp** [comment] 2016-01-06 15:58
yes, as planned.

**Comment by tomolimo** [comment] 2016-01-06 15:59
If yes, then you are ready to start your first PM process creation!
I can help too: just ask for it.
I invite you to re-read this: https://forge.glpi-project.org/projects/processmaker/wiki/Concept

**Comment by tomolimo** [comment] 2016-01-06 16:00
Thank you for the tests: I'll update the wiki accordingly
thank you again,
Tomolimo

**Comment by easjrgrp** [comment] 2016-01-06 16:04
OK. thank you so much.
Now I have too much things to fun !
thank you again,
Everaldo

**Comment by easjrgrp** [comment] 2016-01-06 16:16
When will be avaliable the version of the plugin for GLPI 0.90?

**Comment by tomolimo** [comment] 2016-01-06 16:24
Certainly before end of January 2016.

**Comment by tomolimo** [comment] 2016-03-10 19:21
Could you please start a new issue? 
I'll be able to help you tomorrow 8:00 UTC+1.

**Comment by tomolimo** [comment] 2016-03-11 07:15
Anyway, as far as I can see, you didn't respect this comment: https://github.com/tomolimo
delete any '/' trailing at the end of the URL.
regards,
Tomolimo

**Closed** 2016-03-14 11:03 UTC
